# Generated by Django 5.1.2 on 2024-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='fees_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid')], max_length=100, null=True),
        ),
    ]
