# Generated by Django 5.1.2 on 2024-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_alter_fees_fees_status_alter_fees_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned')], max_length=10, null=True),
        ),
    ]
